[project]
name = "rfcdash"
version = "0.1.0"
description = "Tools for generating a Dash Docset of RFCs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "html5lib>=1.1",
]
