#!/bin/sh

cd RFCs.docset/Contents/Resources/Documents

httrack http://tools.ietf.org/rfc/mini-index \
  --display=2 --timeout=60 --retries=99 --sockets=7 \
  --connection-per-second=5 --max-rate=250000 \
  --keep-alive --depth=2 --mirror --robots=0 \
  --user-agent '$(httrack --version); rfcdash (https://wjn.me/c/rfcdash)' \
  "+tools.ietf.org/images/*" "+tools.ietf.org/html/*" "-tools.ietf.org/html/draft-*"
